tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "jkfran/killport"
tap "lokalise/cli-2"
tap "osx-cross/arm"
tap "osx-cross/avr"
tap "oven-sh/bun"
tap "qmk/qmk"
brew "libgit2"
brew "bat"
brew "bottom"
brew "gettext"
brew "cloc"
brew "cmake"
brew "curl"
brew "libtool"
brew "krb5"
brew "php"
brew "composer"
brew "coreutils"
brew "eza"
brew "fd"
brew "fend"
brew "flac"
brew "nettle"
brew "unbound"
brew "gnutls"
brew "ffmpeg"
brew "ncurses"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "pinentry"
brew "gnupg"
brew "go"
brew "imagemagick"
brew "jq"
brew "lpeg"
brew "make"
brew "mas"
brew "n"
brew "ninja"
brew "pinentry-mac"
brew "pkg-config"
brew "pnpm"
brew "postgresql@14", restart_service: true
brew "rbenv"
brew "ripgrep"
brew "ruby"
brew "rustup-init"
brew "stow"
brew "trash"
brew "wget"
brew "zellij"
brew "zoxide"
brew "jkfran/killport/killport"
brew "lokalise/cli-2/lokalise2"
brew "oven-sh/bun/bun"
brew "qmk/qmk/qmk"
cask "alacritty"
cask "alfred"
cask "figma"
cask "font-montserrat"
cask "hazel"
cask "keka"
cask "logi-options-plus"
cask "losslesscut"
cask "mimestream"
cask "raspberry-pi-imager"
cask "rekordbox"
cask "setapp"
mas "Cardhop", id: 1290358394
mas "Compressor", id: 424390742
mas "Discovery", id: 1381004916
mas "Fantastical", id: 975937182
mas "Magnet", id: 441258766
mas "Reeder", id: 1529448980
mas "Sequel Ace", id: 1518036000
mas "Shazam", id: 897118787
mas "Streaks", id: 963034692
mas "Todoist", id: 585829637
mas "Webcam Settings", id: 533696630
mas "Xcode", id: 497799835
mas "‎WhatsApp", id: 310633997
