tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "jkfran/killport"
tap "wez/wezterm"
brew "libgit2"
brew "bat"
brew "bottom"
brew "gettext"
brew "cloc"
brew "cmake"
brew "curl"
brew "libtool"
brew "krb5"
brew "php"
brew "composer"
brew "coreutils"
brew "eza"
brew "fd"
brew "fend"
brew "flac"
brew "nettle"
brew "unbound"
brew "gnutls"
brew "ffmpeg"
brew "ncurses"
brew "fish"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "gitui"
brew "glow"
brew "gnu-sed"
brew "pinentry"
brew "gnupg"
brew "go"
brew "goreleaser"
brew "helix"
brew "httpie"
brew "imagemagick"
brew "jq"
brew "lpeg"
brew "mas"
brew "mosh"
brew "n"
brew "neovim", args: ["HEAD"]
brew "ninja"
brew "pinentry-mac"
brew "pkg-config"
brew "postgresql@14", restart_service: true
brew "ripgrep"
brew "rustup-init"
brew "trash"
brew "wget"
brew "xplr"
brew "zellij"
brew "zoxide"
brew "jkfran/killport/killport"
cask "alacritty"
cask "alfred"
cask "backblaze"
cask "figma"
cask "hazel"
cask "keka"
cask "logi-options-plus"
cask "losslesscut"
cask "macs-fan-control"
cask "mimestream"
cask "monitorcontrol"
cask "obs"
cask "raspberry-pi-imager"
cask "rekordbox"
cask "setapp"
cask "transmission"
cask "wezterm-nightly"
mas "Cardhop", id: 1290358394
mas "Compressor", id: 424390742
mas "Craft", id: 1487937127
mas "Fantastical", id: 975937182
mas "Magnet", id: 441258766
mas "Reeder", id: 1529448980
mas "Shazam", id: 897118787
mas "Todoist", id: 585829637
mas "Webcam Settings", id: 533696630
