local wezterm = require("wezterm")
local act = wezterm.action

return {
	send_composed_key_when_right_alt_is_pressed = false,
	send_composed_key_when_left_alt_is_pressed = true,
	disable_default_key_bindings = true,
	-- disable_default_mouse_bindings = true,
	keys = {
		{ key = "Enter", mods = "ALT", action = act.ToggleFullScreen },
		{ key = "0", mods = "SUPER", action = act.ResetFontSize },
		{ key = "-", mods = "SUPER", action = act.DecreaseFontSize },
		{ key = "=", mods = "SUPER", action = act.IncreaseFontSize },
		{ key = "L", mods = "SHIFT|CTRL", action = act.ShowDebugOverlay },
		{ key = "M", mods = "SHIFT|CTRL", action = act.Hide },
		{ key = "N", mods = "SHIFT|CTRL", action = act.SpawnWindow },
		{ key = "Q", mods = "CTRL", action = act.QuitApplication },
		{ key = "Q", mods = "SHIFT|CTRL", action = act.QuitApplication },
		{ key = "R", mods = "CTRL", action = act.ReloadConfiguration },
		{ key = "R", mods = "SHIFT|CTRL", action = act.ReloadConfiguration },
		{ key = "c", mods = "SUPER", action = act.CopyTo("Clipboard") },
		{ key = "h", mods = "SUPER", action = act.HideApplication },
		{ key = "k", mods = "SUPER", action = act.ClearScrollback("ScrollbackOnly") },
		{
			key = "l",
			mods = "SHIFT|SUPER",
			action = act.ShowLauncherArgs({ flags = "FUZZY|LAUNCH_MENU_ITEMS|DOMAINS" }),
		},
		{ key = "m", mods = "SUPER", action = act.Hide },
		{ key = "n", mods = "SUPER", action = act.SpawnWindow },
		{ key = "q", mods = "SUPER", action = act.QuitApplication },
		{ key = "v", mods = "SUPER", action = act.PasteFrom("Clipboard") },
		{ key = "w", mods = "SUPER", action = act.CloseCurrentTab({ confirm = true }) },
		{ key = "Copy", mods = "NONE", action = act.CopyTo("Clipboard") },
		{ key = "Paste", mods = "NONE", action = act.PasteFrom("Clipboard") },
	},

	key_tables = {
		copy_mode = {
			-- { key = "Tab", mods = "NONE", action = act.CopyMode("MoveForwardWord") },
			-- { key = "Tab", mods = "SHIFT", action = act.CopyMode("MoveBackwardWord") },
			-- { key = "Enter", mods = "NONE", action = act.CopyMode("MoveToStartOfNextLine") },
			-- { key = "Escape", mods = "NONE", action = act.CopyMode("Close") },
			-- { key = "Space", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "Cell" }) },
			-- { key = "$", mods = "NONE", action = act.CopyMode("MoveToEndOfLineContent") },
			-- { key = "$", mods = "SHIFT", action = act.CopyMode("MoveToEndOfLineContent") },
			-- { key = ",", mods = "NONE", action = act.CopyMode("JumpReverse") },
			-- { key = "0", mods = "NONE", action = act.CopyMode("MoveToStartOfLine") },
			-- { key = ";", mods = "NONE", action = act.CopyMode("JumpAgain") },
			-- { key = "F", mods = "NONE", action = act.CopyMode({ JumpBackward = { prev_char = false } }) },
			-- { key = "F", mods = "SHIFT", action = act.CopyMode({ JumpBackward = { prev_char = false } }) },
			-- { key = "G", mods = "NONE", action = act.CopyMode("MoveToScrollbackBottom") },
			-- { key = "G", mods = "SHIFT", action = act.CopyMode("MoveToScrollbackBottom") },
			-- { key = "H", mods = "NONE", action = act.CopyMode("MoveToViewportTop") },
			-- { key = "H", mods = "SHIFT", action = act.CopyMode("MoveToViewportTop") },
			-- { key = "L", mods = "NONE", action = act.CopyMode("MoveToViewportBottom") },
			-- { key = "L", mods = "SHIFT", action = act.CopyMode("MoveToViewportBottom") },
			-- { key = "M", mods = "NONE", action = act.CopyMode("MoveToViewportMiddle") },
			-- { key = "M", mods = "SHIFT", action = act.CopyMode("MoveToViewportMiddle") },
			-- { key = "O", mods = "NONE", action = act.CopyMode("MoveToSelectionOtherEndHoriz") },
			-- { key = "O", mods = "SHIFT", action = act.CopyMode("MoveToSelectionOtherEndHoriz") },
			-- { key = "T", mods = "NONE", action = act.CopyMode({ JumpBackward = { prev_char = true } }) },
			-- { key = "T", mods = "SHIFT", action = act.CopyMode({ JumpBackward = { prev_char = true } }) },
			-- { key = "V", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "Line" }) },
			-- { key = "V", mods = "SHIFT", action = act.CopyMode({ SetSelectionMode = "Line" }) },
			-- { key = "^", mods = "NONE", action = act.CopyMode("MoveToStartOfLineContent") },
			-- { key = "^", mods = "SHIFT", action = act.CopyMode("MoveToStartOfLineContent") },
			-- { key = "b", mods = "NONE", action = act.CopyMode("MoveBackwardWord") },
			-- { key = "b", mods = "ALT", action = act.CopyMode("MoveBackwardWord") },
			-- { key = "b", mods = "CTRL", action = act.CopyMode("PageUp") },
			-- { key = "c", mods = "CTRL", action = act.CopyMode("Close") },
			-- { key = "f", mods = "NONE", action = act.CopyMode({ JumpForward = { prev_char = false } }) },
			-- { key = "f", mods = "ALT", action = act.CopyMode("MoveForwardWord") },
			-- { key = "f", mods = "CTRL", action = act.CopyMode("PageDown") },
			-- { key = "g", mods = "NONE", action = act.CopyMode("MoveToScrollbackTop") },
			-- { key = "g", mods = "CTRL", action = act.CopyMode("Close") },
			-- { key = "h", mods = "NONE", action = act.CopyMode("MoveLeft") },
			-- { key = "j", mods = "NONE", action = act.CopyMode("MoveDown") },
			-- { key = "k", mods = "NONE", action = act.CopyMode("MoveUp") },
			-- { key = "l", mods = "NONE", action = act.CopyMode("MoveRight") },
			-- { key = "m", mods = "ALT", action = act.CopyMode("MoveToStartOfLineContent") },
			-- { key = "o", mods = "NONE", action = act.CopyMode("MoveToSelectionOtherEnd") },
			-- { key = "q", mods = "NONE", action = act.CopyMode("Close") },
			-- { key = "t", mods = "NONE", action = act.CopyMode({ JumpForward = { prev_char = true } }) },
			-- { key = "v", mods = "NONE", action = act.CopyMode({ SetSelectionMode = "Cell" }) },
			-- { key = "v", mods = "CTRL", action = act.CopyMode({ SetSelectionMode = "Block" }) },
			-- { key = "w", mods = "NONE", action = act.CopyMode("MoveForwardWord") },
			-- {
			-- 	key = "y",
			-- 	mods = "NONE",
			-- 	action = act.Multiple({ { CopyTo = "ClipboardAndPrimarySelection" }, { CopyMode = "Close" } }),
			-- },
			-- { key = "PageUp", mods = "NONE", action = act.CopyMode("PageUp") },
			-- { key = "PageDown", mods = "NONE", action = act.CopyMode("PageDown") },
			-- { key = "LeftArrow", mods = "NONE", action = act.CopyMode("MoveLeft") },
			-- { key = "LeftArrow", mods = "ALT", action = act.CopyMode("MoveBackwardWord") },
			-- { key = "RightArrow", mods = "NONE", action = act.CopyMode("MoveRight") },
			-- { key = "RightArrow", mods = "ALT", action = act.CopyMode("MoveForwardWord") },
			-- { key = "UpArrow", mods = "NONE", action = act.CopyMode("MoveUp") },
			-- { key = "DownArrow", mods = "NONE", action = act.CopyMode("MoveDown") },
		},

		search_mode = {
			-- { key = "Enter", mods = "NONE", action = act.CopyMode("PriorMatch") },
			-- { key = "Escape", mods = "NONE", action = act.CopyMode("Close") },
			-- { key = "n", mods = "CTRL", action = act.CopyMode("NextMatch") },
			-- { key = "p", mods = "CTRL", action = act.CopyMode("PriorMatch") },
			-- { key = "r", mods = "CTRL", action = act.CopyMode("CycleMatchType") },
			-- { key = "u", mods = "CTRL", action = act.CopyMode("ClearPattern") },
			-- { key = "PageUp", mods = "NONE", action = act.CopyMode("PriorMatchPage") },
			-- { key = "PageDown", mods = "NONE", action = act.CopyMode("NextMatchPage") },
			-- { key = "UpArrow", mods = "NONE", action = act.CopyMode("PriorMatch") },
			-- { key = "DownArrow", mods = "NONE", action = act.CopyMode("NextMatch") },
		},
	},

	mouse_bindings = {
		{
			event = { Down = { streak = 1, button = "Left" } },
			action = act.SelectTextAtMouseCursor("Cell"),
		},
		{
			event = { Down = { streak = 1, button = "Left" } },
			mods = "SHIFT",
			action = act.ExtendSelectionToMouseCursor("Cell"),
		},
		{
			event = { Down = { streak = 1, button = "Left" } },
			mods = "ALT",
			action = act.SelectTextAtMouseCursor("Block"),
		},
		{
			event = { Down = { streak = 1, button = "Left" } },
			mods = "SHIFT|ALT",
			action = act.ExtendSelectionToMouseCursor("Block"),
		},
		{
			event = { Down = { streak = 1, button = "Middle" } },
			action = act.PasteFrom("PrimarySelection"),
		},
		{
			event = { Down = { streak = 1, button = { WheelUp = 1 } } },
			action = act.ScrollByCurrentEventWheelDelta,
		},
		{
			event = { Down = { streak = 1, button = { WheelDown = 1 } } },
			action = act.ScrollByCurrentEventWheelDelta,
		},
		{
			event = { Down = { streak = 2, button = "Left" } },
			action = act.SelectTextAtMouseCursor("Word"),
		},
		{
			event = { Down = { streak = 3, button = "Left" } },
			action = act.SelectTextAtMouseCursor("Line"),
		},
		{
			event = { Drag = { streak = 1, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Cell"),
		},
		{
			event = { Drag = { streak = 1, button = "Left" } },
			mods = "ALT",
			action = act.ExtendSelectionToMouseCursor("Block"),
		},
		{
			event = { Drag = { streak = 1, button = "Left" } },
			mods = "SHIFT|CTRL",
			action = act.StartWindowDrag,
		},
		{
			event = { Drag = { streak = 1, button = "Left" } },
			mods = "SUPER",
			action = act.StartWindowDrag,
		},
		{
			event = { Drag = { streak = 2, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Word"),
		},
		{
			event = { Drag = { streak = 3, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Line"),
		},
		{
			event = { Up = { streak = 1, button = "Left" } },
			action = act.CompleteSelectionOrOpenLinkAtMouseCursor("ClipboardAndPrimarySelection"),
		},
		{
			event = { Up = { streak = 1, button = "Left" } },
			mods = "SHIFT",
			action = act.CompleteSelectionOrOpenLinkAtMouseCursor("ClipboardAndPrimarySelection"),
		},
		{
			event = { Up = { streak = 1, button = "Left" } },
			mods = "ALT",
			action = act.CompleteSelection("ClipboardAndPrimarySelection"),
		},
		{
			event = { Up = { streak = 1, button = "Left" } },
			mods = "SHIFT|ALT",
			action = act.CompleteSelectionOrOpenLinkAtMouseCursor("PrimarySelection"),
		},
		{
			event = { Up = { streak = 2, button = "Left" } },
			action = act.CompleteSelection("ClipboardAndPrimarySelection"),
		},
		{
			event = { Up = { streak = 3, button = "Left" } },
			action = act.CompleteSelection("ClipboardAndPrimarySelection"),
		},
		{
			event = { Down = { streak = 1, button = "Left" } },
			action = act.SelectTextAtMouseCursor("Cell"),
		},
		{
			mods = "SHIFT",
			event = { Down = { streak = 1, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Cell"),
		},
		{
			mods = "ALT",
			event = { Down = { streak = 1, button = "Left" } },
			action = act.SelectTextAtMouseCursor("Block"),
		},
		{
			mods = "SHIFT|ALT",
			event = { Down = { streak = 1, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Block"),
		},
		{
			event = { Down = { streak = 1, button = "Middle" } },
			action = act.PasteFrom("PrimarySelection"),
		},
		{
			event = { Down = { streak = 2, button = "Left" } },
			action = act.SelectTextAtMouseCursor("Word"),
		},
		{
			event = { Down = { streak = 3, button = "Left" } },
			action = act.SelectTextAtMouseCursor("Line"),
		},
		{
			event = { Drag = { streak = 1, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Cell"),
		},
		{
			mods = "ALT",
			event = { Drag = { streak = 1, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Block"),
		},
		{
			mods = "SHIFT|CTRL",
			event = { Drag = { streak = 1, button = "Left" } },
			action = act.StartWindowDrag,
		},
		{
			mods = "SUPER",
			event = { Drag = { streak = 1, button = "Left" } },
			action = act.StartWindowDrag,
		},
		{
			event = { Drag = { streak = 2, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Word"),
		},
		{
			event = { Drag = { streak = 3, button = "Left" } },
			action = act.ExtendSelectionToMouseCursor("Line"),
		},
		{
			event = { Up = { streak = 1, button = "Left" } },
			action = act.CompleteSelectionOrOpenLinkAtMouseCursor("ClipboardAndPrimarySelection"),
		},
		{
			mods = "SHIFT",
			event = { Up = { streak = 1, button = "Left" } },
			action = act.CompleteSelectionOrOpenLinkAtMouseCursor("ClipboardAndPrimarySelection"),
		},
		{
			mods = "ALT",
			event = { Up = { streak = 1, button = "Left" } },
			action = act.CompleteSelection("ClipboardAndPrimarySelection"),
		},
		{
			mods = "SHIFT|ALT",
			event = { Up = { streak = 1, button = "Left" } },
			action = act.CompleteSelectionOrOpenLinkAtMouseCursor("PrimarySelection"),
		},
		{
			event = { Up = { streak = 2, button = "Left" } },
			action = act.CompleteSelection("ClipboardAndPrimarySelection"),
		},
		{
			event = { Up = { streak = 3, button = "Left" } },
			action = act.CompleteSelection("ClipboardAndPrimarySelection"),
		},
	},
}
